### ISSUE TITLE
Blocks broken by hand break faster than without the mod

### ISSUE THREAD

**Issue by codetaylor** [tyra314/ToolProgression#13]
MC: 1.12.2
Forge: 14.23.1.2554
ToolProgression: 1.4.1

**Behavior:**
Breaking a block with an empty hand, or a hand with a non-tool item held, breaks the block faster than breaking the same block without the mod. Tested with a grass block, dirt block, and log block.

**Expected behavior:**
Breaking a block with an empty hand, or a hand with a non-tool item held, breaks the block at the same rate as vanilla or forge-modded without the mod.

**How to reproduce:**
Load the above versions of Forge and ToolProgression, break some grass blocks, dirt blocks and log blocks. Next, disable the mod or remove it from the mods folder, load and break the same blocks. Note the speed difference.

**Edit:**
I wanted to mention that this was tested using only the ToolProgression mod and default config files.

**Comment by tyra314** [comment]
Oh, in the case someone makes a block, which is pretty hard to break, like obsidian, harvestable by hands, I added a minimum break speed. Turns out, it is still too less for obsidian but fucks everything else up. For now, I will remove the minimum break speed and later add something to also overwrite the break speed.

**Comment by tyra314** [comment]
Fixed in [v1.4.2](https://minecraft.curseforge.com/projects/tool-progression/files/2503732)
