### ISSUE TITLE
Incompat with WAILA Harvestability - Cobwebs indestructible with any tools

### ISSUE THREAD

**Issue by Vyraal1** [tyra314/ToolProgression#15]
Specifically with cobwebs - it seems to make cobwebs indestructible to swords, shears, bare hands, and any other tools in survival. In creative, even using swords doesn't break cobwebs, but creative hands/items will.

So far other vanilla ores seem to be fine. Also the WAILA tooltip, where you specify the tools, has a capitalization difference at the top between WAILA Harvestability and the one added by Tool Progression.

How to repeat - create an instance with only these mods:
Forge 2559
WAILA 1.8.23
Tool Progression 1.4.3
WAILA Harvestability 1.1.12

**Comment by tyra314** [comment]
First of all, I recommend you, to not use my mod together with WAILA Harvestability. Just don't. The reason is simple. I  had to completely circumvent Vanilla/Forge code paths to make the overwrites fly. WAILA Harvestability is not aware of this, thus it maybe shows wrong information. My mod comes with its own WAILA plugin, use this one instead. Having both is even worse, as they provide similar kind of information, but may tell you different results.

The problem with the cobweb is that WAILA Harvestability [injects changes](https://github.com/squeek502/WailaHarvestability/blob/70a3c89d0c39ea86f8a841dea2e40466956c1641/java/squeek/wailaharvestability/setup/MissingHarvestInfo.java#L14) into vanilla, which my mod then enforces. If you insist on using WAILA Harvestability, you can add a block overwrite to fix the situation:

```
S:"minecraft:web:0"=?sword=0
```

And considering the capitalization difference, I'm not trying to mimic WAILA Harvestability. All I aim for is a basic indication, if you can harvest the block and if not, giving the reason for that.

**Comment by tyra314** [comment]
To add another thought after sleeping other the issue. WAILA Harvestability is probably doing the right thing in theory here, but you also need to add the sword tool class to all swords, which might be hard to do.
