### ISSUE TITLE
Impossible to break a block when the tool I have is not the proper tool...

### ISSUE THREAD

**Issue by Fireztonez** [tyra314/ToolProgression#27]
Hello,
When I add your mod in my pack, all the blocks I can't optain with the tool I use, come unbreakable... I can't find any configuration about that thing, but I realy whant to be possible to break without the appropriate, like in vanilla, but I need to change the harvest level of lot of block's. So, for sure I can't remove your mod, but if you can just fix that or tell me how to fix that!!

Minecraft 1.12.2
Forge 14.23.2.2628
ToolProgression 1.12.2-1.4.7

Thank's
Fireztonez

**Comment by tyra314** [comment]
I'm sorry that is not possible right now and that is intentional. ToolProgression enforces that not harvestable blocks are unbreakable. This behavior is a change from vanilla, but it prevents surprises for players, especially given that I completely circumvent the vanilla harvest checks and therefore most plugins may show wrong harvestability results.

In contrast to this issue, #25 is a very concise issue with one vanilla behavior.

For now, I'm closing this as invalid. As I said, it's on intention.

**Comment by Fireztonez** [comment]
ok, thank's for the reply, this is little bit annoying, but you are probably right, is can fix some bad surprise to the player... Possibly adding a configuration will be a great idee, if is not cause problem, but that's ok....

Fireztonez

**Comment by tyra314** [comment]
With the upcoming version [1.5.1](https://minecraft.curseforge.com/projects/tool-progression/files/2567741) you will be able to define a [new overwrite](https://github.com/tyra314/ToolProgression/wiki/Block-overwrite#destroyability) or use a global option.
