### ISSUE TITLE
Wrenching RFTools blocks destroy them

### ISSUE THREAD

**Issue by NillerMedDild** [tyra314/ToolProgression#33]
Hey!

McJty has recently updated all of his mods, included his library mod. The updates must have changed Wrench behaviour, because when shift-clicking wrenchable blocks, it just destroys them. This did not happen in previous versions. The log doesn't say anything about it.

I've tested this in an instance with only Tool Progression, JEI, RFTools and McJtyLib.

I have also reported this to the RFTools tracker.

toolprogression-1.12.2-1.5.1
rftools-1.12-7.51
mcjtylib-1.12-3.0.0

**Comment by NillerMedDild** [comment]
https://github.com/McJtyMods/RFTools/issues/1776

**Comment by tyra314** [comment]
Should be fine in the upcoming version [1.5.2](https://minecraft.curseforge.com/projects/tool-progression/files/2570720)

**Comment by NillerMedDild** [comment]
Thanks!

**Comment by Ricket** [comment]
Can you reopen this bug and take a look, since it's still an issue per https://github.com/McJtyMods/RFTools/issues/1776 ? I just bumped into it with the Enigmatica 2 Expert pack 1.41, using a Crescent Hammer (Thermal Foundation) on a Crafter Tier 3 (RFtools). It just deleted the crafter, which of course lost all the items and recipes in it.

**Comment by tyra314** [comment]
This should be fixed in the upcoming [v1.5.7](https://minecraft.curseforge.com/projects/tool-progression/files/2636658)
